skaks-opt arena \
  --engine skaks \
  --opponent skaks \
  --games 20 \
  --clock 5.0 \
  --opponent-clock 5.0 \
  --increment 0.1 \
  --opponent-increment 0.1 \
  --limit 100 \
  --concurrency 2 \
  --engine-params /Users/guillem/work/repos/skaks_tuning/play_vs_sunfish/logs/EXPLORE_best.yaml
