skaks-opt arena \
  --engine skaks \
  --opponent sunfish \
  --games 20 \
  --clock 5.0 \
  --opponent-clock 3.0 \
  --increment 0.1 \
  --opponent-increment 0.1 \
  --limit 100 \
  --concurrency 2 \
  --engine-params ../skaks_tuning/play_vs_sunfish/logs/EXPLORE_best.yaml
